using System;
using System.Text;

namespace db_code_test
{
	public class DatabaseModelToPostgreSQL
	{
		public DbCommandSequence DoTransform(Schema srcModel)
		{
			var dstModel = new DbCommandSequence ();
			foreach (var t in srcModel.RemovalSequence)
			{
				Generate_Drop_Statement (dstModel, t);
			}
			foreach (var t in srcModel.CreationSequence)
			{
				Generate_Create_Statement (dstModel, t);
			}
			return dstModel;
		}

		public void Generate_Drop_Statement(DbCommandSequence commands, Table t)
		{
			var statement = new StringBuilder ();
			statement.AppendFormat ("DROP TABLE IF EXISTS \"{0}\";", t.Name);
			commands.CreateCommand (statement.ToString());
		}

		public void Generate_Create_Statement(DbCommandSequence commands, Table t)
		{
			var columnsList = new StringBuilder ();
			foreach (var c in t.Columns)
			{
				if (columnsList.Length != 0)
				{
					columnsList.AppendFormat(",{0}", Environment.NewLine);
				}
				columnsList.AppendFormat ("{0}\"{1}\" {2}", new string(' ',4), c.Name, GetNativeType (c.SpecType));
			}
			var statement = new StringBuilder ();
			statement.AppendFormat ("{2}CREATE TABLE \"{0}\" ({2}{1}{2});", t.Name, columnsList.ToString(), Environment.NewLine);
			commands.CreateCommand (statement.ToString());
		}

		protected string GetNativeType(ColumnType SpecType)
		{
			switch (SpecType.Text)
			{
			case "INTEGER":
				return "DECIMAL";
			case "RATIONAL":
				throw new NotImplementedException ("refactoring is necessary to return 2 fields instead of one");
			case "STRING":
				return "VARCHAR";
				#if false
				// may be it should not present in DLS, and always be autogenerated?
				case "TIMESTAMP": 
				return "TIMESTAMP";
				#endif
			case "DATE":
				return "DATE";
			case "KEY":
				return "INTEGER";
			default:
				throw new ArgumentException (string.Format("SpecType is {0} which is unexpected", SpecType));
			}
		}
	}
}

